import Head from "next/head";
import styles from "../styles/Home.module.css";
import Layout from "../components/Layout";
import Hero from "../components/Hero";
import Service from "../components/Service";
import { client } from "../lib/client";
import Menu from "../components/Menu";
export default function Home({ pizzas }) {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Food Delivery</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Logo.png" />
        </Head>
        <main>
          <Hero />
          <Service />
          <Menu pizzas={pizzas} />
        </main>
      </div>
    </Layout>
  );
}

export const getServerSideProps = async () => {
  const query = "*[_type == 'pizza']";
  const pizzas = await client.fetch(query);
  return {
    props: {
      pizzas,
    },
  };
};
